// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCriqTQqZv3yIcHhmU3_yXLcM5hyLCzZAg',
    appId: '1:305495179760:web:70cd48d5f69e9ce94e9d35',
    messagingSenderId: '305495179760',
    projectId: 'menulist-c3e9c',
    authDomain: 'menulist-c3e9c.firebaseapp.com',
    storageBucket: 'menulist-c3e9c.appspot.com',
    measurementId: 'G-R9HBKY7NXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-DC1obPoY0kgqPr5wxsEaU-xxa63vvM',
    appId: '1:305495179760:android:7045cd66951645014e9d35',
    messagingSenderId: '305495179760',
    projectId: 'menulist-c3e9c',
    storageBucket: 'menulist-c3e9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcFyQ2YnbVOgGxhmbdJLvEQ7t81E7puB4',
    appId: '1:305495179760:ios:0829b12ba240e8a94e9d35',
    messagingSenderId: '305495179760',
    projectId: 'menulist-c3e9c',
    storageBucket: 'menulist-c3e9c.appspot.com',
    iosClientId: '305495179760-mmrsqo6iltph1ua780uv7tr8a42e6kpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnueFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcFyQ2YnbVOgGxhmbdJLvEQ7t81E7puB4',
    appId: '1:305495179760:ios:0829b12ba240e8a94e9d35',
    messagingSenderId: '305495179760',
    projectId: 'menulist-c3e9c',
    storageBucket: 'menulist-c3e9c.appspot.com',
    iosClientId: '305495179760-mmrsqo6iltph1ua780uv7tr8a42e6kpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cnueFoodApp',
  );
}
